POST http://localhost:5001/users
Content-Type: application/json

{
    "name":"Juan",
    "email":"juan@gmail.com",
    "password":"123456",
    "confPassword":"123456",
    "role": "user"
}

###
GET POST http://localhost:5001/me